
package fi.arcusys.koku.palvelut.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "VeeraServicesFacadeWS", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/")
public interface VeeraServicesFacadeWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createCategory", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.CreateCategory")
    @ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.CreateCategoryResponse")
    public void createCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        VeeraCategoryDTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createForm", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.CreateForm")
    @ResponseWrapper(localName = "createFormResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.CreateFormResponse")
    public void createForm(
        @WebParam(name = "arg0", targetNamespace = "")
        VeeraFormDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fi.arcusys.koku.palvelut.ws.client.VeeraCategoryDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCategoriesByCompanyId", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindAllCategoriesByCompanyId")
    @ResponseWrapper(localName = "findAllCategoriesByCompanyIdResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindAllCategoriesByCompanyIdResponse")
    public List<VeeraCategoryDTO> findAllCategoriesByCompanyId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fi.arcusys.koku.palvelut.ws.client.VeeraCategoryDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCategoryByEntryAndCompanyId", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindCategoryByEntryAndCompanyId")
    @ResponseWrapper(localName = "findCategoryByEntryAndCompanyIdResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindCategoryByEntryAndCompanyIdResponse")
    public VeeraCategoryDTO findCategoryByEntryAndCompanyId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<fi.arcusys.koku.palvelut.ws.client.VeeraCategoryDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findChildCategories", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildCategories")
    @ResponseWrapper(localName = "findChildCategoriesResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildCategoriesResponse")
    public List<VeeraCategoryDTO> findChildCategories(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fi.arcusys.koku.palvelut.ws.client.VeeraFormDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findChildForms", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildForms")
    @ResponseWrapper(localName = "findChildFormsResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildFormsResponse")
    public List<VeeraFormDTO> findChildForms(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<fi.arcusys.koku.palvelut.ws.client.VeeraFormDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findChildFormsByFormHolders", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildFormsByFormHolders")
    @ResponseWrapper(localName = "findChildFormsByFormHoldersResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildFormsByFormHoldersResponse")
    public List<VeeraFormDTO> findChildFormsByFormHolders(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<FormHolderDTO> arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findChildFormsCount", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildFormsCount")
    @ResponseWrapper(localName = "findChildFormsCountResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindChildFormsCountResponse")
    public List<Object> findChildFormsCount(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns fi.arcusys.koku.palvelut.ws.client.VeeraFormDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFormByEntryId", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindFormByEntryId")
    @ResponseWrapper(localName = "findFormByEntryIdResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindFormByEntryIdResponse")
    public VeeraFormDTO findFormByEntryId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<fi.arcusys.koku.palvelut.ws.client.VeeraFormDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFormsByDescription", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindFormsByDescription")
    @ResponseWrapper(localName = "findFormsByDescriptionResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.FindFormsByDescriptionResponse")
    public List<VeeraFormDTO> findFormsByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCategoryByEntryAndCompanyId", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.RemoveCategoryByEntryAndCompanyId")
    @ResponseWrapper(localName = "removeCategoryByEntryAndCompanyIdResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.RemoveCategoryByEntryAndCompanyIdResponse")
    public int removeCategoryByEntryAndCompanyId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFormByEntryId", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.RemoveFormByEntryId")
    @ResponseWrapper(localName = "removeFormByEntryIdResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.RemoveFormByEntryIdResponse")
    public int removeFormByEntryId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCategory", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.UpdateCategory")
    @ResponseWrapper(localName = "updateCategoryResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.UpdateCategoryResponse")
    public void updateCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        VeeraCategoryDTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateForm", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.UpdateForm")
    @ResponseWrapper(localName = "updateFormResponse", targetNamespace = "http://facade.palvelut.palvelukanava.koku.arcusys.fi/", className = "fi.arcusys.koku.palvelut.ws.client.UpdateFormResponse")
    public void updateForm(
        @WebParam(name = "arg0", targetNamespace = "")
        VeeraFormDTO arg0);

}
