package com.ixonos.koku.kks.utils.enums;

public enum KehitystietoTyyppi {

  NELJA_VUOTISTARKASTUS, VARHAISKASVATUSSUUNNITELMA, TUKITARVE, LAPSEN_KEHITYS, TERVEYDEN_TILA, KASVATUSTA_OHJAAVAT_TIEDOT, MITTAUS
}
